name = 'Pehe'
license = 'MIT'
licenselink = 'https://github.com/eallion/pehe/blob/dev/LICENSE'
description = 'Pehe : Pehtheme-hugo Enhanced. Bugs fixed. Features refined. This is a Hugo theme is inspired by Material Design v3, built with love using Tailwind CSS v4.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/eallion/pehe'

# If you have a running demo of the theme
demosite = 'https://www.eallion.com/'

# Taxonomy terms
tags = ['blog', 'responsive', 'light', 'tailwindcss']
features = ['tailwindcss', 'two-column', 'sidebar', 'horizontal-menu']

# If the theme has multiple authors

[author]
  name = 'Charles Chin'
  homepage = 'https://www.eallion.com/'
